app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField,PasswordField,SubmitField
from wtforms.validators import DataRequired

class NewMember(FlaskForm):
        new_user= StringField('Nombre del nuevo miembro',validators=[DataRequired()])
        password = PasswordField('Contraseña de registro',validators=[DataRequired()])
        create_user=SubmitField('Agregar Miembro')

app/__init__.py
#Sirve para manejar  la creacion de la app desde afuera del main .py

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
import os

from .auth import auth

from .config import Config


app= Flask(__name__)


app.config.from_object(Config)
db=SQLAlchemy(app)


from .members import members


def create_app():
    
    with app.app_context():
        db.create_all()
    bootsrap = Bootstrap(app)
    app.register_blueprint(auth)
    app.register_blueprint(members)

    return app

app/members/__init__.py
from flask import Blueprint

members =Blueprint('members', __name__, url_prefix='/members')
from . import routes

app/members/routes.py
from . import members
from flask import render_template,abort
from flask import request,session,flash
from models.socio import socio
from app.forms import NewMember
import datetime 
from app import db
from sqlalchemy.exc import IntegrityError


import random
import re





DTM_PASSWORD = 'DCP_DTM_VERACRUZ'



@members.route("/add", methods=["GET", "POST"])



# def Socios():

#     response= make_response(redirect('/'))
#     user_ip = request.remote_addr
#     session['user_ip']= user_ip

#     user_ip=session.get(user_ip)


#     # response.set_cookie('user_ip',user_ip)
#     return response


def AddUser():
    now = datetime.datetime.now()
    new_member = NewMember()
    username = session.get("username")
  
    

    if new_member.validate_on_submit():
        username = new_member.new_user.data
        new_user = request.form['new_user']
        password = request.form['password']

        if DTM_PASSWORD==password:
            session["username"] = username 
            member=socio(new_user)
            try:
                db.session.add(member)
                db.session.commit()
            except IntegrityError as e:
                
                return render_template(
        "members.html",error=e,new_member=new_member
    )
    
                
                
           
            flash("Nuevo socio registrado correctamente")
            return render_template(
        "members.html",contraseña=password, time=now, new_member=new_member, usuario=username
    )

        else:
             flash("Contraseña incorrecta... no se ha podido guardar al nuevo miembro")
             return render_template(
        "members.html",contraseña=password, time=now, new_member=new_member, usuario=username
    )
        
   
   

    return render_template(
        "members.html", time=now, new_member=new_member, usuario=username
    )
@members.route("/chosenMembers", methods=["GET"])  ## route recibe la ruta donde queremos correr la función
def chosen_members():
    print("LAKSJDLASKDJKLS")
    
    arreglo_nombres_aleatorio=[]
    array_members=db.session.query(socio.name).all()
    now = datetime.datetime.now()
    longitud_arreglo_nombres=len(array_members)
    if len(array_members)<6:
        return {'plantilla':'Error'}
    while len(arreglo_nombres_aleatorio)<=6:
        numero_aleatorio=random.randint(0,longitud_arreglo_nombres-1    )
        if not array_members[numero_aleatorio] in arreglo_nombres_aleatorio:
            arreglo_nombres_aleatorio.append(array_members[numero_aleatorio])
            
        else:
            continue

    arreglo_nombres_aleatorio2=list(arreglo_nombres_aleatorio)
    arreglo_final=[]
    
    

    for element in arreglo_nombres_aleatorio2:
        element=str(element)
        arreglo_final.append(re.findall(r"[a-zA-Z ]+.\b",element))
    
    diccionario_final={'persona1':str(arreglo_final[0]).strip("['']"),
                       'persona2':str(arreglo_final[1]).strip("['']"),
                       'persona3':str(arreglo_final[2]).strip("['']"),
                       'persona4':str(arreglo_final[3]).strip("['']"),
                       'persona5':str(arreglo_final[4]).strip("['']"),
                       'persona6':str(arreglo_final[5]).strip("['']"),
                       'persona7':str(arreglo_final[6]).strip("['']")}
    
    
        
        
    
    
    return {'plantilla':render_template("index.html", time=now,members=diccionario_final)}

app/templates/general-info.html
{%    extends 'index.html'   %}

{% from 'bootstrap/form.html' import render_form as render_form %}

{% block content %}
{% for message  in get_flashed_messages() %}
    
{%endfor%}


{% block scripts%}
{{bootstrap.load_js()}}
{% endblock %}


{% endblock content %}

app/templates/index.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/style.css')}}"
    />
    <title>Toastmasters Rols Assign</title>
    <link rel="icon" type="images/x-icon" href="../static/images/toastmaster_logo.ico">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
   
  </head>

    <div class="flex">
      <nav class="nav" style="background-color: #e8e8e8">
        <div class="titulo">
          <nav class="nada">
            <img
              src="{{url_for('static', filename='images/toasmaster_L_letras.png')}}"
            />
          </nav>
        </div>
      </nav>
    </div>

    <span class="placeholder col-12"></span>
    {% block content %}

    <body id="reemplazo">

      
      <figure id="cuatro">
        <blockquote class="blockquote">
          <p>Proxima Sesión:</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          {{time.strftime('%d/%m/%Y')}}<i class="bi bi-calendar-week"></i>
          <cite title="Source Title">No faltes</cite>
        </figcaption>
        <button type="button" class="btn btn-dark position-relative">
            <a class="a"href="{{url_for('members.AddUser')}}">REGISTRAR MIEMBRO</a>
          <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
            <span class="visually-hidden">New alerts</span>
          </span>
        </button>

      </figure>
      
     
      <div id="uno">
        <section class="cargo">
          <h2>
            Campanero<img
              src="{{url_for('static', filename='images/Campanero2.png')}}"
            />
            <p>{{members.persona4}}</p>
          </h2>
          <h2>
            E.Gramatical<img
              src="{{url_for('static', filename='images/E.Gramatical.png')}}"
            />
            <p>{{members.persona3}}</p>
          </h2>
          <h2>
            E.General<img
              src="{{url_for('static', filename='images/Evaluador General.png')}}"
            /><p>{{members.persona2}}</p>
          </h2>
        </section>
        <section class="cargo">
          <h2>
            Toastmaster
            <img
              src="{{url_for('static', filename='images/Toastmaster.png')}}"
            />
            <p>{{members.persona1}}</p>
          </h2>
          
          <script>   async function  api(){
            const plantilla=  await fetch('https://flaskapp-production-31af.up.railway.app/members/chosenMembers')
            const plantilla2=await plantilla.json()
            return plantilla2

          }

          
          
            </script>

          

          <button onclick="api().then(data=> 
          {if(data.plantilla=='Error')
          {
            alert('Faltan usuarios por registrar deben ser minimo 6')}
          else {document.body.innerHTML=data.plantilla}})
          .catch(error=>console.log(error.meesage))"
            type="button"
            class="btn btn-outline-secondary"
          >Delegar
          </button>
          
          
        

          <div class="logo">
            <img 
              src="{{url_for('static', filename='images/toastmaster_logo.png')}}"
              class=""
              alt="Imagen_logo"
            />
          </div>
        </section>
        <section class="cargo">
          <h2>
            Cronometrador<img
              src="{{url_for('static', filename='images/Semaforo2.png')}}"
            />
            <p>{{members.persona5}}</p>
          </h2>
          <h2>
            D. de Temas<img
              src="{{url_for('static', filename='images/D.Temas_Improvisados.png')}}"
            />
            <p>{{members.persona6}}</p>
          </h2>
          <h2>
            Educativa<img
              src="{{url_for('static', filename='images/Educativa.png')}}"
            />
            <p>{{members.persona7}}</p>
          </h2>
        </section>
      </div>
      {% endblock content %}
    </body>

    <span class="placeholder col-12"></span>
  
    
   
   
  
</html>

app/templates/members.html
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0/css/"
/>
{%    extends 'index.html'   %}

{% from 'bootstrap/form.html' import render_form as render_form %}


{% block content %}




    
    
   <div class="flex-column d-flex justify-content-sm-center align-items-center mt-3 ">
    <button type="button" class="btn btn-dark position-relative mb-2">
        <a class="a" href="{{url_for('Toastmaster')}}">Regresar al Inicio</a>
        </button>
        
       
       <div class="d-flex justify-content-sm-center  ">{{ render_form(new_member) }}</div>
    </div>
    {% for message  in get_flashed_messages() %}
        

    <div class="container d-flex justify-content-sm-center align-items-center" >
        {% if contraseña=="DCP_DTM_VERACRUZ" %}
        
        <div class="alert alert-success alert-dismissible  mt-5">
            {{message}}
            <button  class="btn btn-succes position-absolute top-0 end-0" style="width: 40px; height: 57px;"  type="button" data-dismiss="alert" class="close"> &times;</button>
            
        </div>
        {%else%}

        
        <div class="alert alert-danger alert-dismissible mt-5">
            {{message}}
            <button  class="btn btn-danger position-absolute top-0 end-0" style="width: 40px; height: 57px;"  type="button" data-dismiss="alert" class="close"> &times;</button>
            
        
        </div>
        {% endif %}
        {% endfor%}
    </div>
    
    
    <p class="d-flex justify-content-sm-center mt-5">CONTRASEÑA DE REGISTRO=<strong>DCP_DTM_VERACRUZ</strong></p>

    {% if error %}

    <p class="d-flex justify-content-sm-center mt-5"> <strong>USUARIO YA REGISTRADO ANTERIORMENTE PRUEBA CON OTRO NOMBRE </strong></p>
    {% endif %}
    

    

    


{% block scripts%}
{{bootstrap.load_js()}}
{% endblock %}


{% endblock content %}